### PR TITLE
WIP feat(MOPLAT-399): WebView back button is in wrong position

### PR DESCRIPTION
**Pull request by patrinoua**
### Description

This PR resolves [MOPLAT-399]
Screen Shot 2022-08-24 at 16 59 22

### PR Checklist
- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.
### To the reviewers 👀
- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

[MOPLAT-399]: https://artsyproduct.atlassian.net/browse/MOPLAT-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by patrinoua** [comment]
@brainbicycle it was 1 story point after all! 😄

**Comment by rajsam003** [comment]
The issue is addressed here https://github.com/artsy/energy/pull/151

**Comment by patrinoua** [comment]
> The issue is addressed in #151
@rajsam003 let's maybe try to avoid doing things two times in the future 🙈
This PR was there 2 days and https://github.com/artsy/energy/pull/151 was opened 1 hour ago.

**Comment by patrinoua** [comment]
Also there was a ticket for this pr but no ticket for https://github.com/artsy/energy/pull/151 . Maybe we can make a ticket before addressing things in the future in order to avoid doing things that overlap.

**Pull request merged**
