### PR TITLE
palette sync eigen->energy

### PR DESCRIPTION
**Pull request by pvinis**
This PR resolves []

### Description

I removed all tests, stories, and Pill, Message, Cards. They are more tangled in eigen than I care to fix right now, so we can do that when we need them, or when we separate palette-mobile out.

### PR Checklist

- [x] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look on our [docs], or get in touch with us.

[docs]: /docs/README.md

### CODE REVIEW

**Comment by patrinoua** [comment]
This pr is being replaced by other smaller prs right?

**Comment by pvinis** [comment]
cleaned up and ready. changes are only on palette, shared, and a dep that was needed.

**Review by admbtlr — APPROVED** [review]
LGTM!

**Comment by patrinoua** [comment]
massive, perfect, thanks! 🎉

**Pull request merged**
