### PR TITLE
@sarahscott => Adds a dangerfile

### PR DESCRIPTION
**Pull request by orta**
Initial work on a Dangerfile.

re: https://github.com/artsy/mobile/issues/31

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | PR is classed as Work in Progress




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by orta** [comment]
OK, added support for CHANGELOG stuff, and I've removed slather, as it wasn't being used too.

**Comment by orta** [comment]
If I get a "no changelog" fail, then everything is :+1:

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by orta** [comment]
Yep, this is :shipit: 
screen shot 2016-01-07 at 11 57 31

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by sarahscott** [comment]
:+1:

**Pull request merged**
