### PR TITLE
Use latest fonts repos

### PR DESCRIPTION
**Pull request by orta**
Uses the same font techniques introduced in https://github.com/artsy/emission/pull/471 https://github.com/artsy/emission/pull/465 https://github.com/artsy/eigen/pull/2241

### CODE REVIEW

**Comment by orta** [comment]
Turns out I can't GitHub right now

**Comment by orta** [comment]
Looks like it provides a wider font for the avant garde: https://eigen-ci.s3.amazonaws.com/307/index.html

Will update snapshots.

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
OK

**Comment by orta** [comment]
RIP git repo size

**Pull request merged**
