### PR TITLE
@orta=> logout process for new settings panel

### PR DESCRIPTION
**Pull request by sarahscott**
So I used the exact same logout process for the old settings panel and it seems to work well here, but it has no tests. Should I test it? And if so, would it make sense to mock the app delegate?

### CODE REVIEW

**Comment by sarahscott** [comment]
#45

**Comment by orta** [comment]
At this PR it's not strictly your job to add tests to the logout, though you're obviously welcome to do it. 

You could DI in your own app-delegate-conforming object and verify that the logout function is called when it's tapped to ensure the settings calls it. Which is enough to cover this case. Then separately adding some tests to the app delegate would be interesting, be careful not to log yourself out in the sim, which eigen does when you run tests :dancers:

**Comment by sarahscott** [comment]
So the way I built the settings master view controller is not at all testing-friendly. I think I'll make a new PR that moves some things around to make it easier to test in general, and will add a test for logout there.

**Comment by sarahscott** [comment]
Might even be worth it to throw in a view model 0_o

**Pull request closed without merging**
