### PR TITLE
chore: remove vscode settings from gitignore

### PR DESCRIPTION
**Pull request by patrinoua**
### Description

adds .vscode/settings from gitignore so we can have different settings if we wish to 

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

### CODE REVIEW

**Comment by pvinis** [comment]
I'm ok with this change if others are also ok.

but even better, these settings should be part of the user settings, and keep the repo settings minimal. so I wonder, what is different in your settings? what do you want to change from the current setup?

**Comment by patrinoua** [comment]
I agree that there should be repo settings and user settings, but so far I only found this settings thing which I guess is ok if we consider it as our personal user settings, taking into account also that we have set eslint rules that will make sure everyone uses the same code styling.

The thing I want to change is to add a color to the repo so I can easily distinguish between them as many times I have multiple projects open (eg energy, energy1, eigen). I had made a pr about that some months ago so we can broadly do that but it was not accepted, however I find this very helpful!

Screen Shot 2022-09-19 at 13 20 38

**Comment by admbtlr** [comment]
I think this is OK. If we want to have workspace settings in the future, we could create a `settings.default.json` or `settings.example.json` file so that people can create their own.

**Comment by pvinis** [comment]
I would prefer we removed the settings from this repo completely, so that we all get our user settings applied, and if we find issues we can agree on a setting and add it in the repo. so basically i would just remove the file and skip the gitignore addition, but its not a huge issue. Ill merge, and we can revisit if we ever need it 👍 .

**Comment by admbtlr** [comment]
But please change the name - oh too late :(
It should be ADD settings to gitignore, not remove

**Comment by pvinis** [comment]
i changed it here, but yea.. to late for git 🤷

**Pull request merged**
