### PR TITLE
Remove warnings, and update to Xcode 8 recommended settings

### PR DESCRIPTION
**Pull request by orta**
This doesn't remove all warnings, brings it down to 2 + storyboards.

However, that's good enough to work with. Will take a look at the storyboards, but that's gnarly territory.

### CODE REVIEW

**Comment by ArtsyOpenSource** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by orta** [comment]
Only 2 fails, not bad.

**Comment by orta** [comment]
@jonallured I'm cool with merging this now - note, you'll need to update to use 10.3 on an iPad Air 2 I the sim.

**Comment by orta** [comment]
Alright - that should make it not intermittent 👍

**Pull request merged**
