### PR TITLE
feat: upgrades and skeleton reanim fix

### PR DESCRIPTION
**Pull request by pvinis**
This PR resolves [MOPLAT-]

### Description

updated palette mostly

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

### CODE REVIEW

**Review by damassi — APPROVED** [review]

**Comment by damassi** [comment]
Looks like there's a build failure in CI @pvinis, otherwise LGTM 👍

**Review by ArtsyOpenSource — APPROVED** [review]
👍

**Comment by brainbicycle** [comment]
> 👍

nice one Brian, 🤦

**Review by brainbicycle — APPROVED** [review]

**Comment by pvinis** [comment]
> 👍 

what an honor 😝

**Pull request merged**
