### PR TITLE
Migrate to CocoaPods 1.0 +  frameworks

### PR DESCRIPTION
**Pull request by orta**
Alright, this greens locally.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Warning
    ------------- | ------------
        :warning: | Needs testing on a Phone if change is non-trivial
    

  

  


<p align="right" meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://github.com/KrauseFx/danger/">danger</a>
</p>

**Comment by orta** [comment]
Fail is legit

**Comment by orta** [comment]
This doesn't show locally. Hrm.

**Comment by orta** [comment]
I can come back to this another time.

**Pull request closed without merging**
