### PR TITLE
@orta=>Fixed inventory id bug

### LINKED ISSUE #20: Inventory ID not displaying correctly in artwork metadata view
String is getting cut off for inventory IDs that include ampersands.

### PR DESCRIPTION
**Pull request by sarahscott**
fixes #20

### CODE REVIEW

**Comment by orta** [comment]
Can you make a test for this too pleassssee

**Comment by sarahscott** [comment]
yeees

**Comment by orta** [comment]
awesome, a legit fail :+1:

**Comment by orta** [comment]
And green

**Pull request merged**
