### PR TITLE
fix: broken sentry sourcemaps

### PR DESCRIPTION
**Pull request by gkartalis**
This PR resolves [PHIRE-598] 

### Description

Came out of the [folio QA](https://www.notion.so/artsy/sentry-sourcemaps-are-NOT-pointing-the-right-place-85be1144cd83470291cf694ee6cd4322?pvs=4) session. 

Seems like we broke sourcemaps ~ 2 months ago while copying over the `fastlane/sentry_fastlane.rb` file that had eigen as project slug 😅

Found the issue in Sentry when checking the uploaded sourcemaps for every project and in `eigen` I noticed this (energy build included there):

Screenshot 2024-02-01 at 11 28 09

bonus fixes: 
- [x] bumps sentry cli to match eigen version
- [x] fixes the `Quit early if Draft PR` flow that was also copied over from eigen and had the same project name.

### PR Checklist

- [x] I have tested my changes on **iOS** and **Android**.
- [x] I have included **screenshots** or **videos**, or I have not changed the UI.
- [x] I have added **tests**, or my changes don't require any.
- [x] I added an **[app state migration]**, or my changes do not require one.
- [x] I have documented any **follow-up work** that this PR will require, or it does not require any.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to **run** this PR on the simulator or device.

Need help with something? Have a look at our [docs], or get in touch with us.

[app state migration]: ../blob/main/docs/adding_state_migrations.md
[feature flag]: ../blob/main/docs/developing_a_feature.md
[docs]: ../blob/main/docs/README.md

[PHIRE-598]: https://artsyproduct.atlassian.net/browse/PHIRE-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gkartalis** [comment]
will test out that the source maps work in both platforms correctly and afterwards will merge

**Comment by gkartalis** [comment]
Android [sourcemap](https://artsynet.sentry.io/issues/4934706789/events/041d10487dcb43f4895ba538e78a1a01/) works ✅

**Comment by gkartalis** [comment]
ios [sourcemap](https://artsynet.sentry.io/issues/4934791303/events/d60f5ca2f4d34e789768148b16493930/) also works now as well! Merging

**Comment by damassi** [comment]
awesome @gkartalis

**Pull request merged**
