### PR TITLE
Update to use testflight for betas

### PR DESCRIPTION
**Pull request by orta**
This brings it in line with how eigen works WRT betas. For full details on that process, see my blog post: http://artsy.github.io/blog/2015/12/15/Automating-Testflight-Deploys/

Notes: 
* It includes #132 
* I had to convert Folio to use an `xcassets` file for the launch images/app icons, or Apple would reject the build for testflight :-/. 
* I've not tested the push from `beta` branch yet
* I did a run through of the documentation too
* You'll have to run `make certs` locally once this PR is merged.

### CODE REVIEW

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Needs testing on a Phone if change is non-trivial




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Needs testing on a Phone if change is non-trivial




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by ArtsyMobile** [comment]
:white_check_mark: | No errors found
  ------------- | ------------ 



  &nbsp; | 1 Warning
  ------------- | ------------ 
    :warning: | Needs testing on a Phone if change is non-trivial




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-07</i>
</p>

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-08</i>
</p>

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-08</i>
</p>

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-08</i>
</p>

**Comment by orta** [comment]
Not sure what's up with Danger. 
But could just be this PR. This is good to go now.

**Comment by orta** [comment]
For people interested in CI build times:

* Travis went from 20 minute builds + lots of random waiting in the OSS build queue ( ~15m. )
* Circle CI just took 4 minutes.

Reasons: We pay for CircleCI, so no build queue. This also means that the folder aching works for both bundler + CocoaPods, meaning setting up the build is basically just compilation + tests.

**Comment by orta** [comment]
Also added a corresponding commit for this PR on eigen: https://github.com/artsy/eigen/pull/1019

**Comment by ArtsyMobile** [comment]
&nbsp; | 1 Error
  ------------- | ------------ 
    :no_entry_sign: | No CHANGELOG changes made



  :white_check_mark: | No warnings found
  ------------- | ------------ 




<p align="right">
  Generated by 
    <a href="https://github.com/KrauseFx/danger">danger</a>
  on 
  <i>2016-01-08</i>
</p>

**Pull request merged**
