### PR TITLE
tooling: some cleanup of tsconfig and package.json

### PR DESCRIPTION
**Pull request by pvinis**
This PR resolves []

### Description

- removing commented out stuff from tsconfig
- removing `private` from package.json
- changing the relay script to be non-watching, and manually watch when we want

### PR Checklist

- [ ] I tested my changes on **iOS** and **Android**.
- [ ] I added screenshots or videos to illustrate my changes.
- [ ] I added Tests and Stories for my changes.

### To the reviewers 👀

- [ ] I would like **at least one** of the reviewers to run this PR on the simulator or device.

<details><summary>Changelog updates</summary>

#### Cross-platform user-facing changes

-

#### iOS user-facing changes

-

#### Android user-facing changes

-

#### Dev changes

-

</details>

Need help with something? Have a look at our [docs], or get in touch with us.

[docs]: /docs/README.md

### CODE REVIEW

**Review by patrinoua — APPROVED** [review]

**Comment by admbtlr** [comment]
So yeah, tooling obviously isn't a conventional commit type. Maybe `build` would've been satisfactory here too?

**Comment by admbtlr** [comment]
Yes, but it's about using standards so that commonly used [tooling](https://github.com/qoomon/git-conventional-commits) works, changelogs can be easily automated - and it's about learning habits that you can take to every OSS repo you work on. 

None of us is alone in the engineering universe, and sometimes it's best to just do what everybody else does.

**Comment by admbtlr** [comment]
`refactor` is also on some conv commit lists, so it's cool

**Comment by admbtlr** [comment]
https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index

**Pull request merged**
