### PR TITLE
Initial work on a network quality observer

### PR DESCRIPTION
**Pull request by orta**
- [x] Rough design
- [x] Finesse design
- [x] Refactor ARLoginViewController to use this
- [x] Tests

Creates a network object that determines the network connectivity when connecting to apple + artsy. Offers a block API for getting an approximation for how good the network is where you are currently.

### CODE REVIEW

**Comment by sarahscott** [comment]
merging :poodle:

**Comment by joeyAghion** [comment]
Hi, sorry for the late comment.

It seems this change corresponds with a huge spike in hits to the `/system/up` API endpoint.



This endpoint pings all dependent systems to generate a comprehensive health picture, and so can be taxing. (Corresponding with the spike, we're now spending ~14% of all server time responding to these requests.) If you just want to confirm connectivity to the Artsy API, `/system/ping` will be a much better choice.

**Comment by joeyAghion** [comment]
Alternatively, is it possible a bug is causing this request to happen more than expected? I'm looking at 20 requests/second right now.

**Comment by orta** [comment]
that definitely sounds like a bug 👍

**Comment by orta** [comment]
I've made an issue on it and added it to the release TODO

**Pull request merged**
